### ISSUE TITLE
두번째 주말 - Scrum 및 Wrap Up 

### ISSUE THREAD

**Issue by seoulboy** [boostcamp-2020/Project18-B-iOS-BoostRunClub#33]
- 드네교 주기: 30분
- 2번의 주기마다 5~10분 휴식
- 진행 시간 : 2 p.m. ~ 7 p.m.

#### Todo

- [x] Flatmap을 사용한  리팩터링
  - viewModel에서의 coordinator 의존성 제거
  - 관련이슈: https://github.com/boostcamp-2020/Project18-B-iOS-BoostRunClub/issues/32
- [x] RunningInfo 화면 UI 구성 
- [x] PrepareRunViewModel 테스트 코드 작성
  - 관련이슈: #35 
- [ ] RunningInfo ViewModel 작성 
- [ ] RunningInfo ViewModel Test 코드 작성
 
---

주말 숙제: viewmodel test code 짜보기
